config/routes.rb
Rails.application.routes.draw do
  root to: 'raffles#index'
  get '/raffle_entries', to: redirect('/')
  resource :raffle_entries, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :raffle, counter_cache: true

  validates :raffle_id, presence: true
  validates :email,
    presence: true,
    length: { maximum: 255 },
    email: { strict_mode: true, allow_blank: true },
    uniqueness: { scope: :raffle_id }
end

app/models/raffle.rb
class Raffle < ApplicationRecord
  has_many :participants

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/raffle_entries_controller.rb
class RaffleEntriesController < ApplicationController
  def create
    @participant = Participant.new(participant_params)
    unless @participant.save
      render 'raffles/index'
    end
  end

  private

  def participant_params
    params.require(:participant).permit(:raffle_id, :email)
  end
end

app/controllers/raffles_controller.rb
class RafflesController < ApplicationController
  def index
    @participant = Participant.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/raffle_entries_helper.rb
module RaffleEntriesHelper
  def calculate_odds(participant)
    count = participant.raffle.participants_count
    pct = 1.0 / count * 100
    number_to_percentage pct, precision: 0
  end
end

app/helpers/raffles_helper.rb
module RafflesHelper
  def all_valid_raffles
    Raffle.all
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Raffle App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
    <div class="container">
      <%= yield %>
      <footer class="my-5 pt-5 text-muted text-center text-small">
        <p class="mb-1">© 2020 Jiri Zajpt</p>
      </footer>
    </div>
  </body>
</html>

app/views/raffle_entries/create.html.erb
<div class="py-5 text-center">
  <h1>Thanks for signing up!</h1>
  <p class="lead">
    Your odds of winning are <%= calculate_odds @participant %>
  </p>
  <p>
    <%= link_to 'Go back', root_url, class: 'btn btn-lg btn-primary' %>
  </p>
</div>

app/views/raffles/index.html.erb
<div class="py-5 text-center">
  <h2>Raffle!</h2>
  <p class="lead">Welcome to Raffle App! Please select raffle you want to
  enter and enter your email address to get a chance to win!</p>
</div>
<main role="main">
  <%= simple_form_for @participant, url: raffle_entries_path do |f| %>
    <%= f.input :email %>
    <%= f.input :raffle_id, collection: all_valid_raffles, prompt: true,
      error: "Please select raffle"%>
    <hr class="mb-4">
    <%= f.button :submit, "Enter raffle!", class: 'btn-primary btn-block btn-lg',
          data: { "disable-with": "Entering..." }%>
  <% end %>
</main>